### ISSUE TITLE
Automate PyPI package upload upon version tag push

### ISSUE THREAD

**Issue by ckreibich** [zeek/package-manager#136]
PyPI has started to warn about the use of user/password auth with accounts that have 2FA, asking to use API tokens instead. Since this will break at some point, we should move to automating the package upload via CI, using a bot token as we do elsewhere.

**Comment by awelzel** [comment]
> zeekscript and zeek-client have a Github workflow that auto-pushes to pypi upon tagging. It'd be nice to bring that to the remaining Python projects. Example [here](https://github.com/zeek/zeek-client/blob/master/.github/workflows/test.yml#L32-L52). There's a Github secret (PYPI_API_TOKEN) that needs to be enabled for every project that uses this.

Mostly bumping/commenting as this topic came up in an internal conversation.

**Comment by awelzel** [comment]
Christian has built that a while ago.
