### ISSUE TITLE
no __load__.zeek file found in package's 'script_dir' : scripts

### ISSUE THREAD

**Issue by HeroS3c-new** [zeek/package-manager#190]
I'm trying to install these packages:
- conn-burst
- http_csp
- http-stalling-detector

But I'm getting this error here: `no __load__.zeek file found in package's 'script_dir' : scripts`, however I can easily install other packages without any sort of problem...

**Comment by bbannier** [comment]
This is not an issue with the package manager, but with the packages. The concrete issue here is that all these packages use the outdated file extensions `.bro` which are not supported anymore (scripts need to be named `.zeek` these days). Additionally the packages should provide a `zkg.meta`, not `bro-pkg.meta` (not supported anymore either).

I am closing this. Please report this to the packages instead. You can find out the repository by searching for the packages in the [package index](https://packages.zeek.org/).
