### ISSUE TITLE
Sphinx misses spaces

### ISSUE THREAD

**Issue by rhaist** [zeek/package-manager#41]
While packaging for debian lintian noticed some malformed man-code. There are multiple occasions where `.B` is not followed by a space, e.g.: 

https://github.com/zeek/package-manager/blob/f74c3d99e5c0c6bd72b20a3b3c13147459924ccc/doc/man/bro-pkg.1#L93

I don't know if you can fix this in the code or sphinx itself.

**Comment by jsiwek** [comment]
Thanks, seems it was fixable in the embedded sphinxarg extension code.  That's in master now.
