### ISSUE TITLE
bro-pkg.meta renamed to zeek-pkg.meta

### ISSUE THREAD

**Issue by terrencegf** [zeek/package-manager#43]
https://github.com/tenzir/zeek-vast/commit/4bab82b226156e8d1c2d175e092c866fa6fab62b is the first bro/zeek package to rename `bro-pkg.meta` to `zeek-pkg.meta`. This causes `bro-pkg` to fail with error message "invalid package: missing bro-pkg.meta metadata file". Since https://packages.bro.org (a.k.a., https://packages.zeek.org) relies on the bro-pkg script to get information, the [bro/tenzir/zeek-vast](https://github.com/tenzir/zeek-vast) package no longer appears on the website.

Until all bro packages are renamed to zeek, the bro-pkg script should look for both `bro-pkg.meta` and `zeek-pkg.meta`.

**Comment by jsiwek** [comment]
Yep, thanks.  It may have to just support both indefinitely since it's kind of up to the packager whether they even want to rename things.  (Generally, we just haven't started changing out 'bro' in places that have functional impact like this, but such changes are planned to happen eventually).

**Comment by jsiwek** [comment]
`bro-pkg.meta` and `zkg.meta` files are now both supported in v2.0.0.
