### ISSUE TITLE
Packaging of bro-pkg into an DEB & RPM

### ISSUE THREAD

**Issue by rbclark** [zeek/package-manager#44]
Currently, any users who need packages in a disconnected environment will have to pull down the source code for bro-pkg and install it using pip. This is less than ideal since the Zeek project has other python based command-line tools which are available as RPM and DEB packages. Would it be possible to get a packaged version of the package manager made available as well? This would provide much easier access to the unbundle command for such users.

**Comment by rhaist** [comment]
I am the maintainer of bro-pkg for Debian and Ubuntu. You can get deb packeges from the archives.

**Comment by rbclark** [comment]
Okay awesome! Is there any chance there is a package for CentOS based distributions as well?

**Comment by rhaist** [comment]
I think @fabaff would be the person to ask for that. He is maintaining bro in Fedora/Epel.

**Comment by rbclark** [comment]
@fabaff would you be willing to consider this request?

**Comment by fabaff** [comment]
There is a Fedora RPM and a package for EPEL. Both are not up-to-date.

For me, it always required a large amount of time to get the RPM packages to state which is usable (more or less). Thus, it's usually not on the top of my todo list.

Almost every package that come out of the bro/zeek ecosystem requires patching to make the build process work. I tried to address those issues maybe five years ago with the development team, wasn't very successful and nowadays it's still looks the same. In the meantime with the renaming it will take an extra amount of time to get everything updated.

Every help with the RPM packages for Fedora/EPEL would be appreciated. Especially when it comes to Package review ;-)

**Comment by jsiwek** [comment]
> Almost every package that come out of the bro/zeek ecosystem requires patching to make the build process work. I tried to address those issues maybe five years ago with the development team, wasn't very successful and nowadays it's still looks the same.

@fabaff five years is a long time, I don't know/remember why the issues weren't addressed then or even what the issues were, but maybe it would be good to bring them up again at the relevant GH repos ?  There's not a conspiracy here to make packaging overly difficult, more likely just a lack of cycles and/or your previous suggestions never got tracked properly (sorry if that's the case).

**Comment by Bialogs** [comment]
@fabaff Do you have the RPM packaging scripts available to share?

**Comment by fabaff** [comment]
@jsiwek, I wouldn't call it a conspiracy, more focusing on the improvement of the tool itself. Running the tools was always possible on Fedora/CentOS with the provided details thus, as for many project, packaging is not "priority number 1." 

@Bialogs, package-manager is not available yet. I started with bifcl.

**Comment by rbclark** [comment]
I understand that it is difficult to get Bro-related packages included in Fedora/EPEL repositories. Is it easier and possible to build and release the RPM with openSUSE similar to how Bro/broctl is distributed? 

https://build.opensuse.org/package/show/network:bro/bro

**Comment by ckreibich** [comment]
Folks I'm going over older `zkg` tickets and for this one I'm wondering whether it's still relevant, for a couple of reasons:
- zkg is included with Zeek itself these days
- folks who'd like to install it independently have a supported way for doing so via `pip install zkg`
- Us providing DEBs / RPMs alone isn't really better than installing `zkg` via `pip` — it'd take providing such packages via the various Linux distros to make it seamless.

I'd very much like to understand the packaging concerns you mentioned above, @fabaff, if you still remember them. Fwiw, @0xxon has mentioned similar concerns, so I'm thinking it'd be good to start compiling a list of improvements that'd help packagers of the various Zeek ecosystem projects.

**Comment by ckreibich** [comment]
Also, our [binary packaging](https://github.com/zeek/zeek/wiki/Binary-Packages) already includes separate `zkg` packages, for nightly Zeek builds, the latest regular release, and LTS releases. See here for examples:

- https://download.opensuse.org/repositories/security:/zeek/xUbuntu_21.04/amd64/zeek-zkg_4.1.0-0_amd64.deb
- https://download.opensuse.org/repositories/security:/zeek/CentOS_8/x86_64/zeek-zkg-4.1.0-1.1.x86_64.rpm
- https://download.opensuse.org/repositories/security:/zeek/Fedora_34/x86_64/zeek-zkg-4.1.0-1.1.x86_64.rpm

This seems to cover the original request in this ticket, so I'll close it.
