### ISSUE TITLE
bro-pkg unbundle does not work on older git versions

### ISSUE THREAD

**Issue by rbclark** [zeek/package-manager#45]
I am attempting to take advantage of the `bro-pkg unbundle` command to install a package offline. I have managed to get bro-pkg installed from pip, however when I run bro-unbundle with any file I end up running into the following problem:

```
# git clone  --depth=1 /root/.bro-pkg/scratch/bundle/dummy-connections /root/.bro-pkg/scratch/dummy-connections --no-single-branch
warning: --depth is ignored in local clones; use file:// instead.
Cloning into '/root/.bro-pkg/scratch/dummy-connections'...
fatal: attempt to fetch/clone from a shallow repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

It looks like `git version 1.8.3.1` which is the latest for RHEL 7.6 does not support cloning from shallow repositories, and bro-pkg tries to use `git clone` to transfer a folder from the `bundle` folder into its parent. Is there any chance of move or copy being used here instead to work around the issue for those of us on distributions using older git versions?

**Comment by jsiwek** [comment]
I pushed a patch to the `master` branch that you can install like:

`pip install git+git://github.com/zeek/package-manager@master`

Let me know if it fixes the issue for you and I'll make a release.

**Comment by jsiwek** [comment]
I just made release v1.5.3 which includes the fix.  Let me know if you still have problems.
