### ISSUE TITLE
Improve non-interactive bro-pkg install

### ISSUE THREAD

**Issue by JonZeolla** [zeek/package-manager#47]
Right now the only way to automate a `bro-pkg install` is via `--force` which has the unwanted side effect of exiting `0` regardless of if it encountered any issues. There should be a way to automate `bro-pkg` installs (i.e. accept all of the default configs) but still surface the appropriate exit codes.

```
[root@31ef4a8dee39 ~]# # The bro package in ./code/ is intentionally broken
[root@31ef4a8dee39 ~]# bro-pkg install code --version master --force
Running unit tests for "/root/code"
error: failed to run tests for /root/code: package build_command failed, see log in /root/.bro-pkg/logs/code-build.log
Installing "/root/code".......
Failed installing "/root/code": package build_command failed, see log in /root/.bro-pkg/logs/code-build.log
[root@31ef4a8dee39 ~]# echo $?
0
```

**Comment by jsiwek** [comment]
Thanks for the report, looks like only a few "failure" code paths had non-zero exit code previously, but now in `master` and `v1.5.6` they should all generally have non-zero exit (let me know if you find any oversights).
