### ISSUE TITLE
Also accept zeek-pkg.meta

### ISSUE THREAD

**Issue by 0xxon** [zeek/package-manager#52]
It turns out that a number of people use zeek-pkg.meta independently of each other (instead of zkg.meta).

Instead of alerting every one of them that is false - could we perhaps just also accept that name for meta files in zkg?

**Comment by jsiwek** [comment]
Would rather not, but will wait a bit to better judge how common a mistake it will be (only current ones w/ the mistake that I count are `emojifier` and `aaalm`, since `zeek-vast` did the renaming way before anything was even formalized/documented).

**Comment by jsiwek** [comment]
Submitted PRs for the effected repos to change filename since it's the easy solution for now:

https://github.com/tenzir/zeek-vast/pull/4
https://github.com/emojifier/emojifier/pull/1
https://github.com/NSkelsey/aaalm/pull/1

**Comment by 0xxon** [comment]
Just as a followup - this happened again - and I admittedly missed it.

#75 is related.

I really would like to have either this in - or at least #75, in cases where repos do this wrong and I miss it (or in cases where a repo messes things up later in the lifetime).

**Comment by jsiwek** [comment]
I prefer relying on #75 to catch these cases, too, and that's now in `zkg v2.4.0`.  I don't think it's worthwhile to accept `zeek-pkg.meta`, so will close this.  The reasons I can see for that mistake happening are:

1) Porting from `bro-pkg.meta`.  There's a finite number of those in existence and so this becomes a non-issue soon enough.
2) The documentation was not read/understood.  In this case, there's no reason to think `zeek-pkg.meta` is the only possible mistaken assumption someone could make.  Just as well could have called it `zeek-package.meta` or any other arbitrary filename.  There could be a policy of "name it anything you want and we'll try to guess what you picked based on whatever file we find first that happens to start with `[package]`, but I'd rather not.
