### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by rsmmr** [zeek/package-manager#54]
When tests fail during install, I get something like this:

```
Running unit tests for "zeek/xxx/yyy"
error: zeek/xxx/yyy tests failed, inspect contents of /home/robin/.zkg/testing/xxx for details
```

When I look into that path, I see:

```
> ls /home/robin/.zkg/testing/xxx
clones  plugins  scripts
```

It would be helpful if the error message pointed right to the directory where the test output is (i.e,m inside `clones/...`)

**Comment by jsiwek** [comment]
Thanks, v2.0.6 now has a better message.
