### ISSUE TITLE
Python2 will fail in here as urllib does not contain a parse method.

### ISSUE THREAD

**Issue by lnxg33k** [zeek/package-manager#60]
https://github.com/zeek/package-manager/blob/b1c038d3424464013206be8baa786625b8de5e56/zeekpkg/manager.py#L402

**Comment by awelzel** [comment]
@lnxg33k - sorry about that. Mind giving #61 a look.

**Comment by jsiwek** [comment]
@awelzel thanks for the patch, it's now in `zkg v2.1.1`

@lnxg33k a comprehensive and explicit *removal* of support for end-of-life'd Python2 is planned in the near-term, so a course of action to take soon should be to get any consumption of `zkg` updated to use Python3
