### ISSUE TITLE
Unnecessary dependency rebuilds

### ISSUE THREAD

**Issue by rsmmr** [zeek/package-manager#70]
I'm confused by something I'm seeing and not sure if that's intended or not:

Assume we have a package `A` that depends on another package `B`. I install `B` manually first: `zkg install B`. Then I do `zkg install A`. It seems that during the unit testing phase of `A`,  `B` gets cloned and built again; l see both packages in `testing/A/clones/{A,B}` and I also saw errors being reported from that build of `B` (the errors were unrelated to this issue, but it shows that the build was happening). I find that surprising and potentially dangerous, as I would expect `A` to test against the already installed version of `B`.

**Comment by rsmmr** [comment]
Hmm, there's more going on here. So this is what I'm seeing. `A` is `spicy-tftp`, B is `spicy-runtime`. The former depends on the latter.

```
# find  ~/.zkg/clones/package/ ~/.zkg/plugin_dir/ /opt/zeek/lib/zeek/plugins/
/root/.zkg/clones/package/
/root/.zkg/plugin_dir/
/root/.zkg/plugin_dir/packages
/root/.zkg/plugin_dir/packages/README
/opt/zeek/lib/zeek/plugins/
```

```
# spicy_version=topic/robin/spicy-runtime zkg install spicy-runtime
[...]
```
# find  ~/.zkg/clones/package/ ~/.zkg/plugin_dir/ /opt/zeek/lib/zeek/plugins/
```
# ls -al /opt/zeek/lib/zeek/plugins
total 0
drwxr-xr-x 1 root zeek 40 Sep 23 12:00 .
drwxr-xr-x 1 root zeek 21 Sep 23 11:54 ..
drwxr-xr-x 3 root root 41 Sep 23 12:00 packages
lrwxrwxrwx 1 root root 70 Sep 23 12:00 Zeek_Spicy -> /root/.zkg/clones/package/spicy-runtime/runtime/lib64/spicy/Zeek_Spicy
```

```
# spicy_version=topic/robin/spicy-runtime zkg install spicy-tftp
[...]
```

```
# ls -al /opt/zeek/lib/zeek/plugins
total 0
drwxr-xr-x 1 root zeek 40 Sep 23 12:07 .
drwxr-xr-x 1 root zeek 21 Sep 23 11:54 ..
drwxr-xr-x 4 root root 59 Sep 23 12:08 packages
lrwxrwxrwx 1 root root 81 Sep 23 12:07 Zeek_Spicy -> /root/.zkg/testing/spicy-tftp/clones/spicy-runtime/runtime/lib64/spicy/Zeek_Spicy
```

This almost looks like it installed the wrong package (i..e, the dependency)? 

Interestingly, it's all still working:

```
# zeek -N
[...]
_Zeek::Spicy - Support for Spicy parsers (*.hlto) (dynamic, version 0.4.0)
Zeek::TFTP - Spicy-based TFTP analyzer (dynamic, version 0.1.0)
```

I believe that's because Zeek is searching through `packages/` as well, where it will eventually find both plugins: 

```
# find /opt/zeek/lib/zeek/plugins/packages/ | grep so$
/opt/zeek/lib/zeek/plugins/packages/spicy-runtime/spicy/src/spicy-build/zeek/plugin/zeek-install-scratch/_Zeek_Spicy/lib/_Zeek-Spicy.linux-x86_64.so
/opt/zeek/lib/zeek/plugins/packages/spicy-runtime/spicy/src/spicy-build/zeek/plugin/lib/_Zeek-Spicy.linux-x86_64.so
/opt/zeek/lib/zeek/plugins/packages/spicy-tftp/lib/Zeek-TFTP.linux-x86_64.so
```

**Comment by rsmmr** [comment]
Update: Doing exactly the same again, I now ended up with a not working version where `packages` was missing for some reason from `/opt/zeek/lib/zeek/plugins`, so that the 2nd `*.so` was not found anymore. Odd.

**Comment by jsiwek** [comment]
> I would expect `A` to test against the already installed version of `B`.

Guess a surface-level explanation for it not doing so is the `True` in this call if you'd like to see what results from toggling it:

https://github.com/zeek/package-manager/blob/2506e4b8d50811262e1c2f64167290a18a8307f1/zeekpkg/manager.py#L2100

Seems to have been set to ignore installed packages since inception of `test`, but presently struggle to find a reason for that being preferable.

**Comment by rsmmr** [comment]
Thanks, that's helpful.  I'll try changing that and see what happens.

**Comment by rsmmr** [comment]
So I figured this all out, it's multiple things coming together:

1. That change to `manager.py` works as expected and now no longer rebuilds the already installed dependency. This sounds like the right approach to me, will file a PR.

2. That  `Zeek_Spicy` link in  `/opt/zeek/lib/zeek/plugins` isn't coming from `zkg` at all; I got confused there. It's the Spicy runtime package that on `make install` puts that in place. That also explains why, with the unpatched zkg, it's suddenly pointing to `testing`: because it got rebuild/installed internally.

3. That missing `packages` in the repeated run comes from me not running `zkg autoconfig` at the beginning. I must have done that the first time I tried all this. Not sure if this difference is expected behavior; it might?

**Comment by jsiwek** [comment]
> 3\. That missing `packages` in the repeated run comes from me not running `zkg autoconfig` at the beginning. I must have done that the first time I tried all this. Not sure if this difference is expected behavior; it might?

If a default config was used without `zkg autoconfig` and I followed right, it seems like maybe an expected result: plugin install path is one of the things that gets configured by that and the default config would just install things into `~/.zkg/`

**Comment by rsmmr** [comment]
To: @jsiwek 

> If a default config was used without `zkg autoconfig` and I followed right, it seems like maybe an expected result: plugin install path is one of the things that gets configured by that and the default config would just install things into `~/.zkg/`

Yeah, that's what happened, and I now see why. What might be a bit confusing is that the docs for `autoconfig` just say "The output of this command is a valid package manager config file". That's correct, but I had forgotten that the config file is needed even for basic Zeek integration because the Zeek paths are configured there (i.e., no config file, no Zeek integration). 

I'm wondering if it would be helpful to change behavior slightly in the absence of a config file to either (1) default the various paths to `zeek-config` if that's available; or (2) at least warn if `zkg` is being used with the config file configuring the paths?

**Comment by jsiwek** [comment]
> I'm wondering if it would be helpful to change behavior slightly in the absence of a config file to either (1) default the various paths to `zeek-config` if that's available; or (2) at least warn if `zkg` is being used with the config file configuring the paths?

Yeah, agree `zkg` could try to be more helpful.  #63 and maybe bits of #68 have matching/related ideas.
