### ISSUE TITLE
Allow non-default branch names

### ISSUE THREAD

**Issue by 0xxon** [zeek/package-manager#76]
This is kind of a continuation of #74.

While the specific problem for #74 is fixed, I also think that we should give people a way to use non-master branches as the default branch in their repository. As mentioned before - there is an increasing push to not use master as the default name in git - and I think that it would be nice to support this.

**Comment by 0xxon** [comment]
To prod a little bit - on this; there have now been three more repositories where the branch had a name different then master. 

So - this is definitely becoming a more common thing and I think we should make this a bit of a priority.

**Comment by 0xxon** [comment]
Note - master is now also no longer the default name that github uses when creating repositories; see https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/

**Comment by jsiwek** [comment]
The zkg 2.5.0 release now has the improved default branch handling logic.
