### ISSUE TITLE
zkg remove considers everything a dependency

### ISSUE THREAD

**Issue by dopheide-esnet** [zeek/package-manager#78]
As mentioned on #packages in Slack, when removing packages I'm getting warnings that every other package is a dependency and will be unloaded.   However, if you proceed, those packages are not actually removed.  Below are two examples:

===== EXAMPLE 1 =====
[root@rg2 dopheide]# zkg list
https://gitlab.es.net/bropkg/find_known_callbacks.git (installed: master)
https://gitlab.es.net/bropkg/http_defacement.git (installed: master)
[root@rg2 dopheide]# zkg info https://gitlab.es.net/bropkg/find_known_callbacks.git
"https://gitlab.es.net/bropkg/find_known_callbacks.git" info:
	url: https://gitlab.es.net/bropkg/find_known_callbacks.git
	versions: []
	install status:
		current_hash = b430e27e9994cd6cf522fda8151db7df0741d03e
		current_version = master
		is_loaded = True
		is_outdated = False
		is_pinned = False
		tracking_method = branch
	metadata file: /root/.zkg/clones/package/find_known_callbacks.git/bro-pkg.meta
	metadata (from version "master"):
		script_dir = scripts
[root@rg2 dopheide]# zkg info https://gitlab.es.net/bropkg/http_defacement.git
"https://gitlab.es.net/bropkg/http_defacement.git" info:
	url: https://gitlab.es.net/bropkg/http_defacement.git
	versions: []
	install status:
		current_hash = 7b9b83b9a7df5a1b10a07400ed1a38164567bbc8
		current_version = master
		is_loaded = True
		is_outdated = False
		is_pinned = False
		tracking_method = branch
	metadata file: /root/.zkg/clones/package/http_defacement.git/bro-pkg.meta
	metadata (from version "master"):
		script_dir = scripts
[root@rg2 dopheide]# zkg remove https://gitlab.es.net/bropkg/http_defacement.git
The following packages will be REMOVED:
  https://gitlab.es.net/bropkg/http_defacement.git
Proceed? [Y/n]
The following installed packages were dependent on the removed package(s) and will be UNLOADED.
  find_known_callbacks.git
Proceed? [N/y] n
Abort.

===== EXAMPLE 2 =====
Here you can see that even with only one package installed, we get prompted twice during removal:

[root@rg2 dopheide]# zkg remove https://gitlab.es.net/bropkg/find_known_callbacks.git
The following packages will be REMOVED:
  https://gitlab.es.net/bropkg/find_known_callbacks.git
Proceed? [Y/n] y
Proceed? [N/y] y

**Comment by jsiwek** [comment]
Thanks for reporting those.  Both the issue of "everything is a dependency" and the structure that lead to the double "Proceed?" prompt should be fixed in zkg v2.4.1 now (the "everything is a dependency" case was outputting all that info incorrectly, but also wasn't truly taking any action related to it).
