### ISSUE TITLE
"zeek: Package not installed" on removal w/  a dependency on zeek version.

### ISSUE THREAD

**Issue by dopheide-esnet** [zeek/package-manager#79]
When  'zeek' is listed as a dependency for a package, when that package is removed, there is a warning that the 'zeek' package is not installed.  

[root@rg2 dopheide]# zkg remove zeek/dopheide/zeek-ntp-monlist
The following packages will be REMOVED:
  zeek/dopheide/zeek-ntp-monlist

Proceed? [Y/n]
The following installed packages were dependent on the removed package(s) and will be UNLOADED.
  zeek-known-hosts-with-dns

Proceed? [N/y] y
Following packages could not be unloaded.
  zeek: Package not installed.

Failed unloading "zeek/dopheide/zeek-ntp-monlist"
Removed "zeek/dopheide/zeek-ntp-monlist"

**Comment by dopheide-esnet** [comment]
Actually, this may  be related to what I was going to make a separate issue.  Dependencies w/ newlines get added into manifest.json with "/n...".    So if you install zeek-ntp-monlist, it's entry will have:

        "metadata": {
          "depends": "\nzeek >=3.0.0-rc1",

That may be causing it to think  'zeek' is a package.

**Comment by jsiwek** [comment]
Should be fixed in zkg v2.4.1, available now.

(The observation about the literal `\n` in the manifest is "fine" since superfluous whitespace gets dropped inside the logic that "parses" that dependency info).
