### ISSUE TITLE
Dependencies on branches don't work when a package doesn't have tags

### ISSUE THREAD

**Issue by ckreibich** [zeek/package-manager#83]
This is a bit funky … I hit it while exploring the use of branches for package dependencies. Here are two packages:

https://github.com/ckreibich/pkg-c
https://github.com/ckreibich/pkg-d

`pkg-c` depends on `pkg-d`, as follows: both packages have a branch `release/1.0`. On that branch, `pkg-c` depends on that branch in `pkg-d`:
```
depends =
    https://github.com/ckreibich/pkg-d branch=release/1.0
```
When I try to install it, zkg doesn't find that version:
```
$ zkg install --version release/1.0 https://github.com/ckreibich/pkg-c
error: failed to resolve dependencies: unsatisfiable dependency "https://github.com/ckreibich/pkg-d": "https://github.com/ckreibich/pkg-c" requires release/1.0
```
Here's the funky part: if you add an arbitrary tag to `pkg-d`, it works. I think the branch-dependency code gets confused by unrelated tag-checking. Here are two other packages:

https://github.com/ckreibich/pkg-e
https://github.com/ckreibich/pkg-f

These are identical to `pkg-c` and `pkg-d` (so `pkg-e` depends on `pkg-f` via branch `release/1.0` as above) except that `pkg-f` also has an arbitrary tag v1.0. With it, the above works:
```
$ zkg install --version release/1.0 https://github.com/ckreibich/pkg-e
The following packages will be INSTALLED:
  https://github.com/ckreibich/pkg-e (release/1.0)

The following dependencies will be INSTALLED:
  https://github.com/ckreibich/pkg-f (release/1.0)

Proceed? [Y/n]
Installing "https://github.com/ckreibich/pkg-e"
Installed "https://github.com/ckreibich/pkg-e" (release/1.0)
Loaded "https://github.com/ckreibich/pkg-e"
Installing "https://github.com/ckreibich/pkg-f"
Installed "https://github.com/ckreibich/pkg-f" (release/1.0)
Loaded "https://github.com/ckreibich/pkg-f"
```

**Comment by jsiwek** [comment]
Thanks, zkg v2.4.2 now includes a patch to address this.
