### ISSUE TITLE
Support installing executables with a package

### ISSUE THREAD

**Issue by rsmmr** [zeek/package-manager#97]
Right now zkg doesn't have any support for installing additional, non-Zeek pieces that come with a package. An example I ran into with https://github.com/zeek/spicy-plugin is an additional binary: the package compiles a tool `spicyz`. That currently ends up inside a deeply hidden directory of the zkg clone tree. Hard to tell users to run it from there. 

Idea: enable a package to specify executables in `zkg.meta`, e.g.:

```
executables = build/bin/spicyz
```

zkg could then create a managed directory `.zkg/bin` and maintain symlinks pointing from that directory to the actual binaries. The symlinks would get in place when a package is installed, and be removed when it's uninstalled. Users would then just once have to put `.zkg/bin` into their PATH and have it working for all packages.

I'm not sure if there could be more general mechanism going beyond just executables, but can't think of anything right now.

**Comment by rsmmr** [comment]
I'll give this a try.

**Comment by jsiwek** [comment]
This is now available in v2.8.0 release.
